import sys, os
import datetime
import shelly

location = "b27"

devices = f"{location}.csv"

with open(f"{location}.glm","w") as fh:
    
    print(f"""// generated by '{' '.join(sys.argv)}' on {datetime.datetime.now()}

module shelly;

class shelly {{
    enumeration {{OFF=0, ON=1}} switch;
    bool output;
    double power[W];
    double voltage[V];
    double current[A];
    double energy[Wh];
    timestamp last_update;
    on_init "python:shelly.init";
}}
""", file=fh)

    for name in shelly.Devices(devices):

        dev = shelly.Shelly(name,devices)
        print(f"""
object shelly {{
    name "{name}";
    output {dev.components['switch:0']['output']};
    power {dev.components['switch:0']['apower']};
    current {dev.components['switch:0']['current']};
    energy {dev.components['switch:0']['aenergy']['total']};
    last_update {dev.components['switch:0']['aenergy']['minute_ts']};
}}
""", file=fh)
        print(f"{name}\n{'-'*len(name)}\n")
        for component,data in dev.components.items():
            print(f"  {component}: {data}")
        print("")
